Damerau–Levenshtein distance
Toflar/state-set-index pull request #4
Opened 2023-10-07 15:55 UTC by ausi

Adds support for transpositions, so that `AB => BA` adds a cost of only 1 instead of 2.

I made it configurable so that using a cost of `2` guarantees to still work the same way as the research paper.

This was more of a thought experiment for me, so feel free to close this PR if you don’t need it ☺️

2023-10-08 12:39 UTC, ausi commented
I added my own implementation of the Damerau-Levenshtein distance in d31170ec7a50f37ee49a7b8281fe9a53637fd83b maybe you can use that to compare it against your automaton variant :)

2023-10-24 15:34 UTC, Toflar reviewed
Love it! I have just pushed a PR to use a Levenshtein-Automaton instead of actually calculating the distance for performance reasons (https://github.com/Toflar/state-set-index/pull/5). So we don't really need to have a distance function in this library anymore but I would still merge it because it can be very useful.

I have some TODOs in https://github.com/Toflar/state-set-index/pull/5, maybe you want to give those a try now that you know the algorithms by heart?

2023-10-24 15:36 UTC, Toflar requested changes

2023-10-24 15:36 UTC, Toflar commented on src/DamerauLevenshtein.php
> +        $string2Length = \strlen($string2);
You should be using `mb_*` functions everywhere in order to support UTF-8 strings.

2023-10-24 15:36 UTC, Toflar commented on tests/DamerauLevenshteinTest.php
> +    public static function distanceProvider(): \Generator {
Should have some UTF-8 strings for tests, you can copy mine from the `LevenshteinTest`.

2024-11-28 23:24 UTC, ausi commented on src/DamerauLevenshtein.php
> +        $string2Length = \strlen($string2);
Done in 0c7c3a5f82e31918555577df6536a011bc4f2893

2024-11-29 08:38 UTC, Toflar approved these changes

2024-11-29 08:38 UTC, merged

2024-11-29 08:38 UTC, Toflar commented
Thank you, @ausi!